plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'it.unipg.gearlab'
    compileSdk 34

    defaultConfig {
        applicationId "it.unipg.gearlab"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        manifestPlaceholders["AIRCRAFT_API_KEY"] = project.AIRCRAFT_API_KEY

        buildConfigField "String", "MAPTILER_API_KEY", "${MAPTILER_API_KEY}"
        buildConfigField "String", "UMBRIA_DIGITALE_RTK_USER", "${UMBRIA_DIGITALE_RTK_USER}"
        buildConfigField "String", "UMBRIA_DIGITALE_RTK_PASSWORD", "${UMBRIA_DIGITALE_RTK_PASSWORD}"
        buildConfigField "String", "UMBRIA_DIGITALE_RTK_SERVERADDRESS", "${UMBRIA_DIGITALE_RTK_SERVERADDRESS}"
        buildConfigField "Integer", "UMBRIA_DIGITALE_RTK_PORT", "${UMBRIA_DIGITALE_RTK_PORT}"
        buildConfigField "String", "UMBRIA_DIGITALE_MOUNTPOINT", "${UMBRIA_DIGITALE_MOUNTPOINT}"

        buildConfigField "Integer", "SIMULATION", "${SIMULATION}"
        buildConfigField "Double", "SIMULATION_LATITUDE", "${SIMULATION_LATITUDE}"
        buildConfigField "Double", "SIMULATION_LONGITUDE", "${SIMULATION_LONGITUDE}"

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildFeatures {
        buildConfig = true
    }

    packaging {
        jniLibs {
            pickFirsts += ['lib/arm64-v8a/libc++_shared.so', 'lib/armeabi-v7a/libc++_shared.so']
            keepDebugSymbols += [
                    "*/*/libconstants.so",
                    "*/*/libdji_innertools.so",
                    "*/*/libdjibase.so",
                    "*/*/libDJICSDKCommon.so",
                    "*/*/libDJIFlySafeCore-CSDK.so",
                    "*/*/libdjifs_jni-CSDK.so",
                    "*/*/libDJIRegister.so",
                    "*/*/libdjisdk_jni.so",
                    "*/*/libDJIUpgradeCore.so",
                    "*/*/libDJIUpgradeJNI.so",
                    "*/*/libDJIWaypointV2Core-CSDK.so",
                    "*/*/libdjiwpv2-CSDK.so",
                    "*/*/libffmpeg.so",
                    "*/*/libFlightRecordEngine.so",
                    "*/*/libvideo-framing.so",
                    "*/*/libwaes.so",
                    "*/*/libagora-rtsa-sdk.so",
                    "*/*/libc++.so",
                    "*/*/libc++_shared.so",
                    "*/*/libmrtc_28181.so",
                    "*/*/libmrtc_agora.so",
                    "*/*/libmrtc_core.so",
                    "*/*/libmrtc_core_jni.so",
                    "*/*/libmrtc_data.so",
                    "*/*/libmrtc_log.so",
                    "*/*/libmrtc_onvif.so",
                    "*/*/libmrtc_rtmp.so",
                    "*/*/libmrtc_rtsp.so"
            ]
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation libs.dji.sdk.v5.aircraft
    compileOnly libs.dji.sdk.v5.aircraft.provided
    runtimeOnly libs.dji.sdk.v5.networkimp

    implementation libs.material
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.slidingpanelayout
    implementation libs.android.sdk
}
